{
    'name': 'MML ROQ Forecast & Procurement Planning',
    'version': '19.0.1.0.0',
    'summary': 'Demand forecasting, ROQ calculation, container consolidation, and 12-month procurement planning',
    'author': 'MML Consumer Products Ltd',
    'website': 'https://www.mmlconsumerproducts.co.nz',
    'category': 'Inventory/Purchase',
    'depends': [
        'mml_base',
        'base', 'sale', 'purchase', 'stock',
        'stock_landed_costs',
    ],
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/roq_port_data.xml',
        'data/ir_cron_data.xml',
        'views/roq_forecast_run_views.xml',
        'views/roq_forecast_line_views.xml',
        'views/roq_shipment_group_views.xml',
        'views/roq_raise_po_wizard_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings_views.xml',
        'views/roq_order_dashboard_views.xml',
        'views/roq_shipment_calendar_views.xml',
        'views/roq_reschedule_wizard_views.xml',
        'views/stock_warehouse_views.xml',
        'views/menus.xml',
        'reports/supplier_order_schedule.xml',
        'reports/supplier_order_schedule_template.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'mml_roq_forecast/static/src/scss/shipment_calendar.scss',
        ],
    },
    'external_dependencies': {
        'python': ['numpy', 'scipy'],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'web_icon': 'mml_roq_forecast,static/description/icon.png',
    'license': 'LGPL-3',
}
